# permissions for end users to view configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: config-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trace-shield-controller
    app.kubernetes.io/part-of: trace-shield-controller
    app.kubernetes.io/managed-by: kustomize
  name: config-viewer-role
rules:
- apiGroups:
  - observability.traceshield.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.traceshield.io
  resources:
  - configs/status
  verbs:
  - get
