---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - observability.traceshield.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.traceshield.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.traceshield.io
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - observability.traceshield.io
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
