apiVersion: observability.traceshield.io/v1alpha1
kind: Config
metadata:
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: config-sample
    app.kubernetes.io/part-of: trace-shield-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trace-shield-controller
  name: config-sample
spec:
  # TODO(user): Add fields here
